### ISSUE TITLE
Unable to test ResNet Model

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#105]
Hi, I just used your code to try to train cityscapes dataset on ResNet; however, when I test the model, it doesn't work. Could you help me to find out why?
Thank you.
No matter I used monodepth_main.py or monodepth_simple.py, both get me the same error.

`python monodepth_main.py --mode test --data_path ~/wonderland/datasets/self/ --filenames_file ~/wonderland/paper_code/monodepth-master/utils/filenames/self_test.txt --log_directory ~/wonderland/monodepth-test-tmp/ --checkpoint_path ~/wonderland/monodepth-tmp/model20180130/model20180130/model-287200`

`$python monodepth_simple.py --image_path ~/wonderland/datasets/KITTI/2011_09_26/2011_09_26_drive_0009_sync/image_02/data/0000000128.jpg --checkpoint_path ~/wonderland/monodepth-tmp/model20180130/model20180130/model-287200`

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 970
major: 5 minor: 2 memoryClockRate (GHz) 1.329
pciBusID 0000:01:00.0
Total memory: 3.94GiB
Free memory: 3.68GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0)
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/weights not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_16/weights not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_16/biases not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
Traceback (most recent call last):
  File "monodepth_simple.py", line 125, in <module>
    tf.app.run()
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 122, in main
    test_simple(params)
  File "monodepth_simple.py", line 83, in test_simple
    train_saver.restore(sess, restore_path)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
	 [[Node: save/RestoreV2_40/_85 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_372_save/RestoreV2_40", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_18', defined at:
  File "monodepth_simple.py", line 125, in <module>
    tf.app.run()
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 122, in main
    test_simple(params)
  File "monodepth_simple.py", line 73, in test_simple
    train_saver = tf.train.Saver()
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/keisha_tsai/wonderland/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key model/decoder/Conv_17/biases not found in checkpoint
	 [[Node: save/RestoreV2_18 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_18/tensor_names, save/RestoreV2_18/shape_and_slices)]]
	 [[Node: save/RestoreV2_40/_85 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_372_save/RestoreV2_40", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by keishatsai** [comment]
After I add the flag `--encoder resent50`, and the program finally ran.
However, the result wasn't that good, while I  test one of image from Cityscapes.
Original:
![cityscapes_munich_000021_000019_leftimg8bit](https://user-images.githubusercontent.com/8175070/35714656-07f301c2-0809-11e8-84eb-97df5bb58be7.png)
Result:
![0_disp](https://user-images.githubusercontent.com/8175070/35714649-fe23b236-0808-11e8-9654-1de169c52088.png)
