### ISSUE TITLE
Data path issue

### ISSUE THREAD

**Issue by kspeng** [mrharicot/monodepth#156]
Dear Author,

I am using citispace dataset - trainextra. I am using windows and try to train the model. However, I got a error message as following:

OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)

It seems that the the code can not get correct data path. I have converted png to jpg. After checking your code, I put all the right and left image in the same folder to match the format. However, the same situation happens. Can you kindly show me how you structure your directory? 

My current data directory looks like this:
..\monodepth
...|___\data
..........|___\citi
..................|___\train
..........................|___\augsburg\augsburg_000000_000000_leftImg8bit.jpg
..........................|___\augsburg\augsburg_000000_000000_rightImg8bit.jpg
..........................|___...
 
My training command line:

python monodepth_main.py --mode train --model_name my_model --data_path data\citi\train\ --filenames_file utils\filenames\cityscapes_train_files.txt --log_directory log\

**Comment by kspeng** [comment]
I have changed the command as this:

python monodepth_main.py --mode train --model_name my_model --data_path c:\workspace\monodepth\data\citi\train\ --filenames_file utils\filenames\cityscapes_train_files.txt --log_directory log\

The situation is still the same. The complete error message is as following:


Traceback (most recent call last):
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)

         [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "monodepth_main.py", line 252, in <module>
    tf.app.run()
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "monodepth_main.py", line 247, in main
    train(params)
  File "monodepth_main.py", line 163, in train
    _, loss_value = sess.run([apply_gradient_op, total_loss])
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)
         [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

Caused by op 'shuffle_batch', defined at:
  File "monodepth_main.py", line 252, in <module>
    tf.app.run()
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "monodepth_main.py", line 247, in main
    train(params)
  File "monodepth_main.py", line 95, in train
    dataloader = MonodepthDataloader(args.data_path, args.filenames_file, params, args.dataset, args.mode)
  File "c:\workspace\monodepth\monodepth_dataloader.py", line 64, in __init__
    params.batch_size, capacity, min_after_dequeue, params.num_threads)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 1300, in shuffle_batch
    name=name)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 846, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 483, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 3799, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\bin\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)
         [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
