### ISSUE TITLE
Trainning issue: cannot create weak reference to 'builtin_function_or_method' object`

### ISSUE THREAD

**Issue by yuli1994** [mrharicot/monodepth#194]
Thanks for your sharing,and I'm trying to train this but get this error:
 commond:
        python monodepth_main.py --mode train --model_name my_model --data_path /home/jiantaoq/ --filenames_file /home/jiantaoq/yuli/monodepth/utils/train.txt --log_directory ./tmp/

> total number of samples: 12614
total number of steps: 19800
Traceback (most recent call last):
  File "monodepth_main.py", line 252, in <module>
    tf.app.run()
  File "/home/jiantaoq/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "monodepth_main.py", line 247, in main
    train(params)
  File "monodepth_main.py", line 95, in train
    dataloader = MonodepthDataloader(args.data_path, args.filenames_file, params, args.dataset, args.mode)
  File "/home/jiantaoq/yuli/monodepth/monodepth_dataloader.py", line 43, in __init__
    left_image_o  = self.read_image(left_image_path)
  File "/home/jiantaoq/yuli/monodepth/monodepth_dataloader.py", line 99, in read_image
    path_length = string_length_tf(image_path)
  File "/home/jiantaoq/yuli/monodepth/monodepth_dataloader.py", line 17, in string_length_tf
    m = tf.py_func(len, [t], tf.int64)
  File "/home/jiantaoq/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 456, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/jiantaoq/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 253, in _internal_py_func
    token = _py_funcs.insert(func)
  File "/home/jiantaoq/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 141, in insert
    self._funcs[token] = func
  File "/usr/lib/python2.7/weakref.py", line 108, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/usr/lib/python2.7/weakref.py", line 278, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'builtin_function_or_method' object

Thanks again

**Comment by yuli1994** [comment]
solved.My tensorflow==1.10.0 ,should be lower,trying 1.5.0 worked.

**Comment by yuli1994** [comment]
> Thanks for your sharing,and I'm trying to train this but get this error:
> commond:
> python monodepth_main.py --mode train --model_name my_model --data_path /home/jiantaoq/ --filenames_file /home/jiantaoq/yuli/monodepth/utils/train.txt --log_directory ./tmp/
> 
> > total number of samples: 12614
> > total number of steps: 19800
> > Traceback (most recent call last):
> > File "monodepth_main.py", line 252, in 
> > tf.app.run()
> > File "/home/jiantaoq/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
> > _sys.exit(main(argv))
> > File "monodepth_main.py", line 247, in main
> > train(params)
> > File "monodepth_main.py", line 95, in train
> > dataloader = MonodepthDataloader(args.data_path, args.filenames_file, params, args.dataset, args.mode)
> > File "/home/jiantaoq/yuli/monodepth/monodepth_dataloader.py", line 43, in **init**
> > left_image_o  = self.read_image(left_image_path)
> > File "/home/jiantaoq/yuli/monodepth/monodepth_dataloader.py", line 99, in read_image
> > path_length = string_length_tf(image_path)
> > File "/home/jiantaoq/yuli/monodepth/monodepth_dataloader.py", line 17, in string_length_tf
> > m = tf.py_func(len, [t], tf.int64)
> > File "/home/jiantaoq/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 456, in py_func
> > func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
> > File "/home/jiantaoq/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 253, in _internal_py_func
> > token = _py_funcs.insert(func)
> > File "/home/jiantaoq/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 141, in insert
> > self._funcs[token] = func
> > File "/usr/lib/python2.7/weakref.py", line 108, in **setitem**
> > self.data[key] = KeyedRef(value, self._remove, key)
> > File "/usr/lib/python2.7/weakref.py", line 278, in **new**
> > self = ref.**new**(type, ob, callback)
> > TypeError: cannot create weak reference to 'builtin_function_or_method' object
> 
> Thanks again
