### ISSUE TITLE
Freezed model in .pb format

### ISSUE THREAD

**Issue by l0stpenguin** [mrharicot/monodepth#203]
Hi, i am looking for a freezed model in .pb format. I found the related issue [181](https://github.com/mrharicot/monodepth/issues/181) was closed but i could not figure out the output node name. Has anyone been able to generate a .pb file which can be shared? I am currently trying to use this to do the process:
``` python
import tensorflow as tf

meta_path = 'model_cityscapes.meta' 
output_node_names = ['output:0']

with tf.Session() as sess:

    # Restore the graph
    saver = tf.train.import_meta_graph(meta_path)

    # Load weights
    saver.restore(sess,tf.train.latest_checkpoint('.'))

    # Freeze the graph
    frozen_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        output_node_names)

    # Save the frozen graph
    with open('output_graph.pb', 'wb') as f:
      f.write(frozen_graph_def.SerializeToString())
```

**Comment by yan99033** [comment]
Hey, check out [this link](https://github.com/yan99033/monodepth-cpp/tree/master/freeze_graph) for more information about the creation of the frozen graph.

I have also modified the monodepth_model.py file, which has been renamed to monodepth.py, in order to properly define the output layer name for future use.

**Comment by mevinDhun** [comment]
> Hey, check out [this link](https://github.com/yan99033/monodepth-cpp/tree/master/freeze_graph) for more information about the creation of the frozen graph.
> 
> I have also modified the monodepth_model.py file, which has been renamed to monodepth.py, in order to properly define the output layer name for future use.

Thanks for the link. I tried running it but it fails. Any suggestions?
```
MacBook-Air:monodepth-cpp mevindhunnooa$ python freeze_graph/freeze_graph.py
Traceback (most recent call last):
  File "freeze_graph/freeze_graph.py", line 59, in <module>
    model = monodepth(arg, 'test', x, None)
TypeError: __init__() takes exactly 4 arguments (5 given)
```

**Comment by yan99033** [comment]
> > Hey, check out [this link](https://github.com/yan99033/monodepth-cpp/tree/master/freeze_graph) for more information about the creation of the frozen graph.
> > I have also modified the monodepth_model.py file, which has been renamed to monodepth.py, in order to properly define the output layer name for future use.
> 
> @yan99033 Thanks for the link. I tried running it but it fails. Any suggestions?
> 
> ```
> MacBook-Air:monodepth-cpp mevindhunnooa$ python freeze_graph/freeze_graph.py
> Traceback (most recent call last):
>   File "freeze_graph/freeze_graph.py", line 59, in <module>
>     model = monodepth(arg, 'test', x, None)
> TypeError: __init__() takes exactly 4 arguments (5 given)
> ```

Thanks for letting me know. I have fixed the error. 

Let me know if you encounter another problem.

**Comment by monkeyking** [comment]
@yan99033 
`mmm@Server:~/Documents/readpb$ python3 freezegit.py 
Traceback (most recent call last):
  File "freezegit.py", line 60, in <module>
    y = model.out
AttributeError: 'monodepth' object has no attribute 'out'`
I just download a copy of your monodepth.py and freeze_graph.py 
and change the ckpt_file and output_dir in freeze_graph.py .
Could you help me.

**Comment by monkeyking** [comment]
@yan99033 
Oh I noticed that the checkpoint format V2 changed,just  pass the prefix works fine.
