### ISSUE TITLE
A error happend when I test the model

### ISSUE THREAD

**Issue by zxnnnn** [mrharicot/monodepth#228]
Hi when I was testing model. I am facing error ValueError: could not broadcast input array from shape (128,256) into shape (256,512). Can someone help me on this ? 
now testing 200 files
Traceback (most recent call last):
  File "monodepth_main.py", line 254, in <module>
    tf.app.run()
  File "/home/zxn/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_main.py", line 251, in main
    test(params)
  File "monodepth_main.py", line 216, in test
    disparities[step] = disp[0].squeeze()
ValueError: could not broadcast input array from shape (128,256) into shape (256,512)

**Comment by MrWXfaster** [comment]
> Hi when I was testing model. I am facing error ValueError: could not broadcast input array from shape (128,256) into shape (256,512). Can someone help me on this ?
> now testing 200 files
> Traceback (most recent call last):
> File "monodepth_main.py", line 254, in
> tf.app.run()
> File "/home/zxn/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "monodepth_main.py", line 251, in main
> test(params)
> File "monodepth_main.py", line 216, in test
> disparities[step] = disp[0].squeeze()
> ValueError: could not broadcast input array from shape (128,256) into shape (256,512)

Hello, do you have a model? I download it according to the author's link. The display page can't be found. If you have one, would you like to share it with me

**Comment by LulaSan** [comment]
This happens to me too! I am not able to find out the error here, I didn't modify anything. Is it possible that anyone tried the test mode?
