### ISSUE TITLE
TEST   KeyError: 'lanczos' 

### ISSUE THREAD

**Issue by Tenacity-soar** [mrharicot/monodepth#36]
When i test the model_kitti ,a problem occured, 

Traceback (most recent call last): File "monodepth_simple.py", line 120, in  tf.app.run() File "/home/akasha/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run _sys.exit(main(_sys.argv[:1] + flags_passthrough)) File "monodepth_simple.py", line 117, in main test_simple(params) File "monodepth_simple.py", line 67, in test_simple input_image = scipy.misc.imresize(input_image, [args.input_height, args.input_width], interp='lanczos') File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 487, in imresize imnew = im.resize(size, resample=func[interp]) 
KeyError: 'lanczos' 

I need help
--

**Comment by Tenacity-soar** [comment]
the problem is i need upgrade the version of scipy. thanks for help.
