### ISSUE TITLE
Error while trying to test it for just one image

### ISSUE THREAD

**Issue by harishannavajjala** [mrharicot/monodepth#48]
Hi,
   I came across your paper recently and I appreciate your work. I am getting an error when I download your pre-existing model and try it on one of my own test images. I appreciate if anybody could help me with this. Thanks.

My command: 
python3 monodepth_simple.py --image_path ~/monodepth/right_image.pgm --checkpoint_path ~/monodepth/model_kitti.data-00000-of-00001

My image specs:
type: .pgm file
dimensions: width = 640,height = 480

Error I get: 

Traceback (most recent call last):
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "monodepth_simple.py", line 117, in <module>
    tf.app.run()
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 114, in main
    test_simple(params)
  File "monodepth_simple.py", line 60, in test_simple
    model = MonodepthModel(params, "test", left, None)
  File "/home/hannavaj/monodepth/monodepth_model.py", line 49, in __init__
    self.build_model()
  File "/home/hannavaj/monodepth/monodepth_model.py", line 291, in build_model
    self.left_pyramid  = self.scale_pyramid(self.left,  4)
  File "/home/hannavaj/monodepth/monodepth_model.py", line 81, in scale_pyramid
    scaled_imgs.append(tf.image.resize_area(img, [nh, nw]))
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 821, in resize_area
    align_corners=align_corners, name=name)
  File "/home/hannavaj/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 499, in apply_op
    repr(values), type(values).__name__))
TypeError: Expected int32 passed to parameter 'size' of op 'ResizeArea', got [<tf.Tensor 'model/truediv:0' shape=() dtype=float64>, <tf.Tensor 'model/truediv_1:0' shape=() dtype=float64>] of type 'list' instead.

**Comment by mrharicot** [comment]
Hi,

Simply remove the extension of the model file you are loading:
python3 monodepth_simple.py --image_path ~/monodepth/right_image.pgm --checkpoint_path ~/monodepth/model_kitti

Also the code was not updated for python3 yet, so I would recommend using python 2.

**Comment by harishannavajjala** [comment]
Thanks !! It worked.
