### ISSUE TITLE
Not able to run monodepth_simple:  Unsuccessful TensorSliceReader constructor

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [mrharicot/monodepth#51]
This is the original issue I had, but I will leave it here as it includes my setup - however the second post below contains the "Unsuccessful TensorSliceReader constructor" error.
---------------------------------------------------------------------

I am having issues running the sample line of code - it looks like perhaps a clash of versions to me, but I am also not too experienced with Tensorflow and the like. Could anyone give me a hanf with where to look?  Thanks in advance!

**I am using this command:**
`python monodepth_simple.py --image_path IMG_20170709_200049.jpg --checkpoint_path ./models/model_kitti`

**I have Tensorflow 1.0, Cuda 8.0 using Python 3.5 (should it be 2.7?) .... _YES!! see next post_
Here is the list of packages in my environent:**

certifi                   2016.2.28                py35_0
cycler                    0.10.0                   py35_0
dbus                      1.10.20                       0
expat                     2.1.0                         0
fontconfig                2.12.1                        3
freetype                  2.5.5                         2
glib                      2.50.2                        1
gst-plugins-base          1.8.0                         0
gstreamer                 1.8.0                         0
icu                       54.1                          0
jpeg                      9b                            0
libffi                    3.2.1                         1
libgcc                    5.2.0                         0
libgfortran               3.0.0                         1
libiconv                  1.14                          0
libpng                    1.6.30                        1
libprotobuf               3.4.0                         0
libxcb                    1.12                          1
libxml2                   2.9.4                         0
matplotlib                2.0.2               np112py35_0
mkl                       2017.0.3                      0
numpy                     1.12.1                   py35_0
openssl                   1.0.2l                        0
pcre                      8.39                          1
pip                       9.0.1                    py35_1
protobuf                  3.4.0                    py35_0
pyparsing                 2.2.0                    py35_0
pyqt                      5.6.0                    py35_2
python                    3.5.4                         0
python-dateutil           2.6.1                    py35_0
pytz                      2017.2                   py35_0
qt                        5.6.2                         5
readline                  6.2                           2
scipy                     0.19.1              np112py35_0
setuptools                36.4.0                   py35_1
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
sqlite                    3.13.0                        0
tensorflow                1.0.1               np112py35_0
tk                        8.5.18                        0
wheel                     0.29.0                   py35_0
xz                        5.2.3                         0
zlib                      1.2.11                        0

**Here is the folder structure (I get the same error running either the Kitti model or the CityScapes):**

├── average_gradients.py
├── bilinear_sampler.py
├── IMG_20170709_200049.jpg
├── LICENSE
├── models
│   ├── model_cityscapes.data-00000-of-00001
│   ├── model_cityscapes.index
│   ├── model_cityscapes.meta
│   ├── model_kitti.data-00000-of-00001
│   ├── model_kitti.index
│   └── model_kitti.meta
├── monodepth_dataloader.py
├── monodepth_main.py
├── monodepth_model.py
├── monodepth_simple.py
├── __pycache__
│   ├── average_gradients.cpython-35.pyc
│   ├── bilinear_sampler.cpython-35.pyc
│   ├── monodepth_dataloader.cpython-35.pyc
│   └── monodepth_model.cpython-35.pyc
├── readme.md
└── utils
    ├── evaluate_kitti.py
    ├── evaluation_utils.py
    ├── filenames
    │   ├── cityscapes_test_files.txt
    │   ├── cityscapes_train_files.txt
    │   ├── cityscapes_val_files.txt
    │   ├── eigen_test_files.txt
    │   ├── eigen_train_files.txt
    │   ├── eigen_val_files.txt
    │   ├── kitti_stereo_2015_test_files.txt
    │   ├── kitti_test_files.txt
    │   ├── kitti_train_files.txt
    │   └── kitti_val_files.txt
    ├── get_model.sh
    └── kitti_archives_to_download.txt

**Here is the full stack trace. It begins with a lot of the same error message (I have omitted a lot), then we see the usual stack trace:**

2017-09-29 02:29:17.740915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2017-09-29 02:29:17.740919: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2017-09-29 02:29:17.740924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
2017-09-29 02:29:18.681968: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.700250: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.716061: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.731301: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.746996: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.759425: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.772928: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.785207: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.797946: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.809876: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
2017-09-29 02:29:18.821502: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
....
....
Traceback (most recent call last):
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "monodepth_simple.py", line 110, in <module>
    tf.app.run()
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 107, in main
    test_simple(params)
  File "monodepth_simple.py", line 53, in test_simple
    model = MonodepthModel(params, "test", left, None)
  File "/home/n1k31t4/sandbox/sigra-prep/depth/monodepth/monodepth_model.py", line 49, in __init__
    self.build_model()
  File "/home/n1k31t4/sandbox/sigra-prep/depth/monodepth/monodepth_model.py", line 291, in build_model
    self.left_pyramid  = self.scale_pyramid(self.left,  4)
  File "/home/n1k31t4/sandbox/sigra-prep/depth/monodepth/monodepth_model.py", line 81, in scale_pyramid
    scaled_imgs.append(tf.image.resize_area(img, [nh, nw]))
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 738, in resize_area
    align_corners=align_corners, name=name)
  File "/home/n1k31t4/anaconda3/envs/depth/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 500, in apply_op
    repr(values), type(values).__name__))
TypeError: Expected int32 passed to parameter 'size' of op 'ResizeArea', got [<tf.Tensor 'model/truediv:0' shape=() dtype=float64>, <tf.Tensor 'model/truediv_1:0' shape=() dtype=float64>] of type 'list' instead.

**Comment by Nicholas-Mitchell** [comment]
**UPDATE:** I found on another thread that you did the work using Python 2.7. 
Upgrading to that got me over the above mentioned error. Now I am getting another error.


**This appears many times:**
tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for W


**Then finally this:**

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
	 [[Node: save/RestoreV2_8 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_8/tensor_names, save/RestoreV2_8/shape_and_slices)]]

**Comment by dleam** [comment]
def scale_pyramid(self, img, num_scales):
        scaled_imgs = [img]
        s = tf.shape(img)
        h = s[1]
        w = s[2]
        for i in range(num_scales - 1):
            ratio = 2 ** (i + 1)
            nh = h // ratio ####
            nw = w // ratio #### @Nicholas-Mitchell 
            scaled_imgs.append(tf.image.resize_area(img, [nh, nw]))
        return scaled_imgs

**Comment by Nicholas-Mitchell** [comment]
@dleam - could you maybe say a few words to your comment? I don't understand how that helps...

**Comment by Nicholas-Mitchell** [comment]
Further attempts to get the simple model working:

I have switched to `tensorflow-gpu` version 1.0.1 (hadn't thought it would be necessary for the simple model test). This still produces the same error, albeit after recognising my graphics card as the device. This came with `cudatoolkit` version 7.xx - so I then updated that to `cudatoolkit` version 8 as used by the authors. This automatically upgraded `tf` to version 1.2.11 and uses CUDNN 5.1. These also still produce the same error as above.

**Comment by Nicholas-Mitchell** [comment]
SUCCESS!

A very simple solution for me - I don't understand how it makes a difference and I couldn't find this problem/solution listed anywhere else: **I just used absolute paths** for all files, so the `--image_path` and also the `--checkpoint_path` flags.

**Comment by Sudonuma** [comment]
Hello, 
I am trying to make the same network work for me but I get this error, 
" Traceback (most recent call last):
  File "monodepth_simple.py", line 110, in <module>
    tf.app.run()
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "monodepth_simple.py", line 107, in main
    test_simple(params)
  File "monodepth_simple.py", line 76, in test_simple
    train_saver.restore(sess, restore_path)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1717, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: " 

DO you have any idea about this?

**Comment by jiawei-mo** [comment]
> Hello,
> I am trying to make the same network work for me but I get this error,
> " Traceback (most recent call last):
> File "monodepth_simple.py", line 110, in 
> tf.app.run()
> File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "monodepth_simple.py", line 107, in main
> test_simple(params)
> File "monodepth_simple.py", line 76, in test_simple
> train_saver.restore(sess, restore_path)
> File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1717, in restore
> + compat.as_text(save_path))
> ValueError: The passed save_path is not a valid checkpoint: "
> 
> DO you have any idea about this?

I solved this problem by using the absolute path.
