### ISSUE TITLE
Error：When try it on my image

### ISSUE THREAD

**Issue by LaiAmy** [mrharicot/monodepth#52]
Hello , 
I just want to try it on my image.
And I download the model cityscapes  . 

I use the command:
python monodepth_simple.py --image_path ~/data/image074.png --checkpoint_path ~/models/model_cityscapes

I got the error ：
Traceback (most recent call last):
  File "monodepth_simple.py", line 110, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 107, in main
    test_simple(params)
  File "monodepth_simple.py", line 57, in test_simple
    input_image = scipy.misc.imresize(input_image, [args.input_height, args.input_width], interp='lanczos')
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 487, in imresize
    imnew = im.resize(size, resample=func[interp])
KeyError: 'lanczos'

My image is png  and is 640*360 .

Could you help me with this problem ~

Thank you .

**Comment by kimjiil** [comment]
i think you don't have lanczos library
in imresize function

**Comment by LaiAmy** [comment]
Oh , Thank you .
It works now .
