### ISSUE TITLE
How can I training on my own data ?

### ISSUE THREAD

**Issue by LaiAmy** [mrharicot/monodepth#54]
How can I training on my data ?
What images should I prepare ?

 I am trying to train this model on my data .
My image size is 640*360.
There are corresponding left and right images in my dataset.
I used the stereo camera to collecting  data .
There are 200 images .

The command ：
python monodepth_main.py --mode train --data_path ~/Documents/my_data/ --filenames_file ./utils/filenames/image_list.txt --input_height 640 --input_width 360

In the image_list.txt ：
left1.jpg right1.jpg
left2.jpg right2.jpg
left3.jpg right3.jpg
.
.
.
left200.jpg right200.jpg

And I got the error ：
-----------------------------------------------------------------------------------------
total number of samples: 200
total number of steps: 1250
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2017-09-25 17:47:17.912541: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 17:47:17.912573: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 17:47:17.912581: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 17:47:17.912586: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 17:47:17.912590: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
number of trainable parameters: 31600072
Traceback (most recent call last):
  File "monodepth_main.py", line 252, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_main.py", line 247, in main
    train(params)
  File "monodepth_main.py", line 163, in train
    _, loss_value = sess.run([apply_gradient_op, total_loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: All dimensions except 3 must match. Input 1 has shape [8 40 23 256] and doesn't match input 0 with shape [8 40 24 256].
         [[Node: gradients/model/decoder/concat_2_grad/ConcatOffset = ConcatOffset[N=2, _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/model/decoder/concat_2_grad/mod, gradients/model/decoder/concat_2_grad/ShapeN, gradients/model/decoder/concat_2_grad/ShapeN:1)]]

Caused by op u'gradients/model/decoder/concat_2_grad/ConcatOffset', defined at:
  File "monodepth_main.py", line 252, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_main.py", line 247, in main
    train(params)
  File "monodepth_main.py", line 117, in train
    grads = opt_step.compute_gradients(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 542, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 348, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 542, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_grad.py", line 194, in _ConcatGradV2
    op, grad, start_value_index=0, end_value_index=-1, dim_index=-1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_grad.py", line 124, in _ConcatGradHelper
    offset = gen_array_ops._concat_offset(non_neg_concat_dim, sizes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 469, in _concat_offset
    shape=shape, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op u'model/decoder/concat_2', defined at:
  File "monodepth_main.py", line 252, in <module>
    tf.app.run()
[elided 1 identical lines from previous traceback]
  File "monodepth_main.py", line 247, in main
    train(params)
  File "monodepth_main.py", line 110, in train
    model = MonodepthModel(params, args.mode, left_splits[i], right_splits[i], reuse_variables, i)
  File "/home/lab418/Documents/Depth/monodepth/monodepth_model.py", line 49, in __init__
    self.build_model()
  File "/home/lab418/Documents/Depth/monodepth/monodepth_model.py", line 302, in build_model
    self.build_vgg()
  File "/home/lab418/Documents/Depth/monodepth/monodepth_model.py", line 205, in build_vgg
    concat5 = tf.concat([upconv5, skip4], 3)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1066, in concat
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 493, in _concat_v2
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): All dimensions except 3 must match. Input 1 has shape [8 40 23 256] and doesn't match input 0 with shape [8 40 24 256].
         [[Node: gradients/model/decoder/concat_2_grad/ConcatOffset = ConcatOffset[N=2, _device="/job:localhost/replica:0/task:0/cpu:0"](gradients/model/decoder/concat_2_grad/mod, gradients/model/decoder/concat_2_grad/ShapeN, gradients/model/decoder/concat_2_grad/ShapeN:1)]]

Is there any step that I am wrong or missing?
Thank you .

**Comment by LaiAmy** [comment]
And how can I test the model on video ?

**Comment by mrharicot** [comment]
The current architecture requires the input sizes to be multiples of 128 for vgg and 64 for resnet50.
To test on a video you will need to extract each frame and test on them independently.
