### ISSUE TITLE
example using kitti resnet failing

### ISSUE THREAD

**Issue by rnunziata** [mrharicot/monodepth#76]
When running test example it works find if I use the vgg checkpoint but fails as follows if I use the kitti resnet when trying to load the pre-trained weights.

Side question: I was wondering if you considered training using DenseNet?

`python monodepth_simple.py --image_path /home/rjn/data/Big_DataSets/VOCdevkit/VOCSDS/img/2008_008237.jpg --checkpoint_path models/model_city2kitti_resnet`

 ```

2017-11-25 16:45:23.879938: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-25 16:45:23.880195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1060
major: 6 minor: 1 memoryClockRate (GHz) 1.733
pciBusID 0000:01:00.0
Total memory: 5.92GiB
Free memory: 5.58GiB
2017-11-25 16:45:23.880210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-11-25 16:45:23.880215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-11-25 16:45:23.880241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
2017-11-25 16:45:24.181037: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [512] rhs shape= [128]
	 [[Node: save/Assign_46 = Assign[T=DT_FLOAT, _class=["loc:@model/encoder/Conv_13/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/encoder/Conv_13/biases, save/RestoreV2_46/_73)]]

.
.
.

Traceback (most recent call last):
  File "monodepth_simple.py", line 110, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 107, in main
    test_simple(params)
  File "monodepth_simple.py", line 76, in test_simple
    train_saver.restore(sess, restore_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512] rhs shape= [128]
	 [[Node: save/Assign_46 = Assign[T=DT_FLOAT, _class=["loc:@model/encoder/Conv_13/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](model/encoder/Conv_13/biases, save/RestoreV2_46/_73)]]

```

**Comment by mrharicot** [comment]
Hi,
You forgot to use the `--encoder resnet50` flag.
