### ISSUE TITLE
Help: keyError: lanczos

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#84]
Hi,

I have tried to test an image by using monodepth_simple.py
but i got this kind of error. I know someone had the same problem as I have now, and it says that I have to upgrade scipy. However, I have already tried to upgrade scipy, I still got the same error message.
my scipy version right now is 1.0.0

Could anyone can help me? 
Thank you
==================================
Traceback (most recent call last):
  File "monodepth_simple.py", line 110, in <module>
    tf.app.run()
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 107, in main
    test_simple(params)
  File "monodepth_simple.py", line 57, in test_simple
    input_image = scipy.misc.imresize(input_image, [args.input_height, args.input_width], interp='lanczos')
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 487, in imresize
    imnew = im.resize(size, resample=func[interp])
KeyError: 'lanczos'

**Comment by mrharicot** [comment]
Hi,
You need to install Pillow (or PIL).
http://pillow.readthedocs.io/en/3.0.x/installation.html

**Comment by keishatsai** [comment]
Thank you for the reply, but I do have Pillow which is version 3.1.2. 
Is there anything else that I haven't noticed?

**Comment by keishatsai** [comment]
just in case...basically, I set up the tensorflow  by using Virtualenv.
this is what I got in my environment:
adium-theme-ubuntu (0.3.4)
backports.weakref (1.0.post1)
bleach (1.5.0)
cycler (0.9.0)
decorator (4.0.6)
enum34 (1.1.6)
funcsigs (1.0.2)
futures (3.2.0)
graphviz (0.8.1)
html5lib (0.9999999)
ipython (2.4.1)
Markdown (2.6.10)
matplotlib (1.5.1)
mock (2.0.0)
mxnet-cu80 (0.11.0)
mxnet-cu80mkl (0.11.0)
numpy (1.13.3)
pbr (3.1.1)
pexpect (4.0.1)
Pillow (3.1.2)
pip (9.0.1)
pkg-resources (0.0.0)
protobuf (3.5.0.post1)
ptyprocess (0.5)
pyparsing (2.0.3)
Pyste (0.9.10)
python-dateutil (2.4.2)
pytz (2014.10)
scipy (1.0.0)
setuptools (38.2.4)
simplegeneric (0.8.1)
six (1.11.0)
tensorflow-gpu (1.4.1)
tensorflow-tensorboard (0.4.0rc3)
unity-lens-photos (1.0)
virtualenv (15.0.1)
Werkzeug (0.13)
wheel (0.30.0)

**Comment by WifiSpy** [comment]
just comment that code like this: 
input_image = scipy.misc.imresize(input_image,  [args.input_height, args.input_width])#, interp='lanczos')

**Comment by keishatsai** [comment]
Hi WifiSpy,
Why should I comment this code? Shouldn't it be part of algorithm?

**Comment by WifiSpy** [comment]
The 'lanczos' method might be not usable in your python environment ,and function 'scipy.misc.imresize()' has a default method to use. Does this help? I also encountered this problem and fixed it by doing this.

**Comment by keishatsai** [comment]
Thank you,WifiSpy.
But it still doesn't work for me......to be specific, here is another error occur.....
my command:: python monodepth_simple.py --image_path ./selfTesting/0000000001.png --checkpoint_path ./models/model_kitti

-----
2017-12-18 09:58:38.024091: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-18 09:58:38.126016: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-18 09:58:38.126317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.329
pciBusID: 0000:01:00.0
totalMemory: 3.94GiB freeMemory: 3.69GiB
2017-12-18 09:58:38.126332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0, compute capability: 5.2)
2017-12-18 09:58:48.986871: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:49.774389: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:50.564366: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:51.354649: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:52.143872: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:52.969552: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:53.786773: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:54.599971: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:55.415238: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:56.214351: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:57.022424: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:57.813571: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:58.635588: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:58:59.440194: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:00.245748: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:01.057152: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:01.865081: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:02.681217: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:03.504683: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:04.302713: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:05.124334: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:05.953518: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:06.765812: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:07.606239: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:08.436703: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:09.243459: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:10.052798: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:10.839671: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:11.648939: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:12.465131: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:13.267418: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:14.064843: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:14.905725: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:15.701720: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:16.510099: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:17.336286: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:18.121846: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:18.937650: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:19.727254: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:20.543942: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:21.346443: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:22.133394: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:22.935817: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:23.755798: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:24.563501: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:25.382651: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:26.187561: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:26.996724: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:27.805798: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:28.609104: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:29.423064: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:30.217353: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:31.018813: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:31.808021: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:32.598618: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:33.409014: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:34.224110: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:35.055983: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:35.868084: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:36.664087: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:37.464530: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:38.279654: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:39.094616: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2017-12-18 09:59:39.807364: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
Traceback (most recent call last):
  File "monodepth_simple.py", line 110, in <module>
    tf.app.run()
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 107, in main
    test_simple(params)
  File "monodepth_simple.py", line 76, in test_simple
    train_saver.restore(sess, restore_path)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]
	 [[Node: save/RestoreV2_10/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_148_save/RestoreV2_10", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save/RestoreV2_3', defined at:
  File "monodepth_simple.py", line 110, in <module>
    tf.app.run()
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "monodepth_simple.py", line 107, in main
    test_simple(params)
  File "monodepth_simple.py", line 66, in test_simple
    train_saver = tf.train.Saver()
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/user_kt/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]
	 [[Node: save/RestoreV2_10/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_148_save/RestoreV2_10", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by WifiSpy** [comment]
Then , you can use this to replace that code: (I just tried this and it works, and you need to import cv2)
input_image=cv2.resize(input_image,(width,height)) 

----- 
(I only tried 'cityscapes' model)

**Comment by keishatsai** [comment]
Thank you for the support, WifiSpy.
It seems work once I comment the "lanczos", but there is still a concern of the difference of interpolation function may generate poor of better result. I gonna try your suggestion to use cv library.

**Comment by WifiSpy** [comment]
Then you can try to add an "interpolation" keyword in function "cv2.resize()" like this to enable "lanczos" :
input_image=cv2.resize(input_image,(width,height),interpolation=cv2.INTER_LANCZOS4)
It works for me.

**Comment by keishatsai** [comment]
Haha I think that error loves me.....
get another error.......

  File "monodepth_simple.py", line 60
    input_image=cv2.resize(input_image,(args.input_width,args.input_height),interpolation=cv2.INTER_LANCZOS4)
    ^
IndentationError: unexpected indent

**Comment by mojoee** [comment]
had the same issue. WifiSpiy's solution works. Just replace scipy package with cv2 and be aware of the permutation of the image(height-->width, width-->height)
