### ISSUE TITLE
global name 'LinearNDInterpolator' is not defined / AttributeError: 'tuple' object has no attribute 'astype'

### ISSUE THREAD

**Issue by keishatsai** [mrharicot/monodepth#98]
Hello, 
I am trying to use linear interpolation provided in code "evaluate_utils.py", 
enable the interpolation at this line 38 in "evaluate_kitti.py"
 `depth = generate_depth_map(gt_calib[t_id], gt_files[t_id], im_sizes[t_id], camera_id, True, True)`
but I got following error message.
Traceback (most recent call last):
  File "utils/evaluate_kitti.py", line 38, in <module>
    depth = generate_depth_map(gt_calib[t_id], gt_files[t_id], im_sizes[t_id], camera_id, True, True)
  File "/home/keisha_tsai/Downloads/monodepth-master/utils/evaluation_utils.py", line 219, in generate_depth_map
    depth_interp = lin_interp(im_shape, velo_pts_im)
  File "/home/keisha_tsai/Downloads/monodepth-master/utils/evaluation_utils.py", line 120, in lin_interp
    f = LinearNDInterpolator(ij, d, fill_value=0)
NameError: global name 'LinearNDInterpolator' is not defined

Does anyone have any idea about this ? Thanks.

**Comment by keishatsai** [comment]
I added import scipy.interpolate, and the case solved.
However, there is another problem occurs

Traceback (most recent call last):
  File "utils/evaluate_kitti.py", line 39, in <module>
    gt_depths.append(depth.astype(np.float32))
AttributeError: 'tuple' object has no attribute 'astype'

seems to there is no variable to receive the value of depth_interp ?
